// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOgKD-TBjFVIFHZFvbfuUw-EvsLzxTz4U',
    appId: '1:905870002255:web:53bcd6a78507f054cf823a',
    messagingSenderId: '905870002255',
    projectId: 'doctor-telehealth',
    authDomain: 'doctor-telehealth.firebaseapp.com',
    storageBucket: 'doctor-telehealth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbI8JLTuvsh7frprMtRD8WvkICQckV3e0',
    appId: '1:905870002255:android:da1bc6da762ce948cf823a',
    messagingSenderId: '905870002255',
    projectId: 'doctor-telehealth',
    storageBucket: 'doctor-telehealth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0b0ElzgFirEz0SUyAO3GYumWUjQeg05E',
    appId: '1:905870002255:ios:a0b9737583fa1a1fcf823a',
    messagingSenderId: '905870002255',
    projectId: 'doctor-telehealth',
    storageBucket: 'doctor-telehealth.firebasestorage.app',
    iosBundleId: 'com.rishab.doctorTelehealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0b0ElzgFirEz0SUyAO3GYumWUjQeg05E',
    appId: '1:905870002255:ios:a0b9737583fa1a1fcf823a',
    messagingSenderId: '905870002255',
    projectId: 'doctor-telehealth',
    storageBucket: 'doctor-telehealth.firebasestorage.app',
    iosBundleId: 'com.rishab.doctorTelehealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOgKD-TBjFVIFHZFvbfuUw-EvsLzxTz4U',
    appId: '1:905870002255:web:7349b3972c61098dcf823a',
    messagingSenderId: '905870002255',
    projectId: 'doctor-telehealth',
    authDomain: 'doctor-telehealth.firebaseapp.com',
    storageBucket: 'doctor-telehealth.firebasestorage.app',
  );
}
